name = "Frienpack"
author = "Nifylau"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "568ef8862e796206b34ac61168cf2b18c5284979a3dff6f4bddeff8ea8275908"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
