name = "Frienpack"
author = "Nifylau"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ddc79abaf7edef5559a4956e20c7c90a082bb9639bbac5611c514e83d80b889"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
