name = "Frienpack"
author = "Nifylau"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb6c1b2ebe596db3feac9dc2955830ad761cb309289909c55e9a128c19971f7e"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
