name = "Frienpack"
author = "Nifylau"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55383d704aaf24f524fadab4bddd26afd14534ba8453150f0ee7f04b54c5b19d"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
