name = "Frienpack"
author = "Nifylau"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "985c25243c6bb6e90411bebd47499fc1febf9881b48e0a3803ebbafdb11413c3"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
