name = "Frienpack"
author = "Nifylau"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2227de1b4e508468ebd12d01e2dc1547cd6d29a8c791b4fdf5fa9ab85d4758f"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
