name = "Frienpack"
author = "Nifylau"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "816160fa96248dae2a869f9255f1982aa1669f4f8371293e1d2a553689b8f620"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
