name = "Frienpack"
author = "Nifylau"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c180f5c0da1a50c418d3083e3b9e59e73fedda85e7000cccbd304d12db39834f"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
