name = "Frienpack"
author = "Nifylau"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d61e38372975580d1c6e72d9d341fb65567ed6237cd265b1ae3f10a8981bb71"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
